### ISSUE TITLE
Crash On Start Up

### ISSUE THREAD

**Issue by SaucissePuree** [BloodyMods/ActuallyAddon#1]
Crash when forge loads
[crash-2018-09-28_08.13.28-client.txt](https://github.com/BloodyMods/ActuallyAddon/files/2426980/crash-2018-09-28_08.13.28-client.txt)

**Comment by BloodWorkXGaming** [comment]
Just released a hotfix version on curse, should be ready soon ^^
For when it is approved:
https://minecraft.curseforge.com/projects/actuallyaddon/files/2621765
