### ISSUE TITLE
Missing Basic Recipes

### ISSUE THREAD

**Issue by Yamza** [BloodyMods/ActuallyAddon#2]
Such as: Nether Quartz  > Prismarine
Rotten Flesh > Leather
https://i.imgur.com/PKtIZcg.png

**Comment by BloodWorkXGaming** [comment]
You don't have any power in your machine apperently ^^
That's why it probably doesn't do anything

Yamza <notifications@github.com> schrieb am Mi., 10. Okt. 2018, 15:49:

**Comment by Yamza** [comment]
Your power bar display doesn't work. :P https://i.imgur.com/F7oHvDO.png

**Comment by BloodWorkXGaming** [comment]
Eeeehmmm.... That's good to know ^^

Yamza <notifications@github.com> schrieb am Mi., 10. Okt. 2018, 16:51:
