### ISSUE TITLE
In survival mode, breaks instantly.

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [BloodyMods/ActuallyAddon#3]
Using Latest Version, i was testing the mod, thought i was in creative but i was in survival.

**Comment by BloodWorkXGaming** [comment]
Uuups... Now that you say that, yeeee, I've forgotten to set that ^^
Thanks :)

Cranky Supertoon <notifications@github.com> schrieb am Do., 11. Okt. 2018,
23:35:

**Comment by CrankySupertoonArchive** [comment]
Also keep note the item is voided, it doesnt even drop

**Comment by CrankySupertoonArchive** [comment]
Keep note a new build isnt on curse yet so this is still a issue
