### ISSUE TITLE
Automation issues

### ISSUE THREAD

**Issue by Mystogrigen** [BloodyMods/ActuallyAddon#4]
I've tried all sorts of ways to automate this block.  I've gotten the Advanced ESD from Actually Additions to insert into the block (with no other block working), and I've been able to use a hopper or Ender IO conduits from the bottom.

The Working Setup:
![2018-10-13_15 21 05](https://user-images.githubusercontent.com/30390280/46909165-f5c14f80-cefb-11e8-9e89-ebb0e694b3f0.png)

Advanced ESD Configuration:
![2018-10-13_15 21 11](https://user-images.githubusercontent.com/30390280/46909166-f9ed6d00-cefb-11e8-92d0-7a7f17fe5994.png)

**Comment by Mystogrigen** [comment]
Nevermind, you insert from sides, withdraw from the bottom.
![2018-10-13_15 36 22](https://user-images.githubusercontent.com/30390280/46909295-d0354580-cefd-11e8-90e8-99f2d1559be0.png)

**Comment by BloodWorkXGaming** [comment]
Sides are insert, top bottom extract

Mystogrigen <notifications@github.com> schrieb am Sa., 13. Okt. 2018, 21:37:
